[[redirects]]
  from = "/314159265358979323846.html"
  to = "/314159265358979323846.html"
  status = 200
  force = true
  conditions = { Role = ["admin"] }

[[headers]]
  for = "/314159265358979323846.html"
  [headers.values]
    Basic-Auth = "admin:test"